//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccuIT.PresentationLayer.WebAdmin.WeddingServiceApp {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WeddingServiceApp.IDreamWedds")]
    public interface IDreamWedds {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDreamWedds/JustSimpleTest", ReplyAction="http://tempuri.org/IDreamWedds/JustSimpleTestResponse")]
        AccuIT.CommonLayer.Aspects.DTO.JsonResponse<string> JustSimpleTest(int number);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDreamWedds/JustSimpleTest", ReplyAction="http://tempuri.org/IDreamWedds/JustSimpleTestResponse")]
        System.Threading.Tasks.Task<AccuIT.CommonLayer.Aspects.DTO.JsonResponse<string>> JustSimpleTestAsync(int number);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDreamWedds/GetWeddingDetailByID", ReplyAction="http://tempuri.org/IDreamWedds/GetWeddingDetailByIDResponse")]
        AccuIT.CommonLayer.Aspects.DTO.JsonResponse<AccuIT.CommonLayer.Aspects.DTO.WeddingDTO> GetWeddingDetailByID(int weddingID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDreamWedds/GetWeddingDetailByID", ReplyAction="http://tempuri.org/IDreamWedds/GetWeddingDetailByIDResponse")]
        System.Threading.Tasks.Task<AccuIT.CommonLayer.Aspects.DTO.JsonResponse<AccuIT.CommonLayer.Aspects.DTO.WeddingDTO>> GetWeddingDetailByIDAsync(int weddingID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDreamWeddsChannel : AccuIT.PresentationLayer.WebAdmin.WeddingServiceApp.IDreamWedds, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DreamWeddsClient : System.ServiceModel.ClientBase<AccuIT.PresentationLayer.WebAdmin.WeddingServiceApp.IDreamWedds>, AccuIT.PresentationLayer.WebAdmin.WeddingServiceApp.IDreamWedds {
        
        public DreamWeddsClient() {
        }
        
        public DreamWeddsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DreamWeddsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DreamWeddsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DreamWeddsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AccuIT.CommonLayer.Aspects.DTO.JsonResponse<string> JustSimpleTest(int number) {
            return base.Channel.JustSimpleTest(number);
        }
        
        public System.Threading.Tasks.Task<AccuIT.CommonLayer.Aspects.DTO.JsonResponse<string>> JustSimpleTestAsync(int number) {
            return base.Channel.JustSimpleTestAsync(number);
        }
        
        public AccuIT.CommonLayer.Aspects.DTO.JsonResponse<AccuIT.CommonLayer.Aspects.DTO.WeddingDTO> GetWeddingDetailByID(int weddingID) {
            return base.Channel.GetWeddingDetailByID(weddingID);
        }
        
        public System.Threading.Tasks.Task<AccuIT.CommonLayer.Aspects.DTO.JsonResponse<AccuIT.CommonLayer.Aspects.DTO.WeddingDTO>> GetWeddingDetailByIDAsync(int weddingID) {
            return base.Channel.GetWeddingDetailByIDAsync(weddingID);
        }
    }
}
