//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccuIT.PersistenceLayer.Repository.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddressMaster
    {
        public int AddressID { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public int Country { get; set; }
        public int PinCode { get; set; }
        public Nullable<int> AddressType { get; set; }
        public Nullable<int> AddressStatus { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> AddressOwnerType { get; set; }
        public Nullable<int> AddressOwnerTypePKID { get; set; }
        public Nullable<int> VenueID { get; set; }
        public string Lattitude { get; set; }
        public string Longitude { get; set; }
    }
}
