//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccuIT.PersistenceLayer.Repository.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyMaster
    {
        public CompanyMaster()
        {
            this.SystemSettings = new HashSet<SystemSetting>();
            this.UserMasters = new HashSet<UserMaster>();
        }
    
        public int CompanyID { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public int DivisionID { get; set; }
    
        public virtual ICollection<SystemSetting> SystemSettings { get; set; }
        public virtual ICollection<UserMaster> UserMasters { get; set; }
    }
}
