//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccuIT.PersistenceLayer.Repository.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyLoginHistory
    {
        public long DailyLoginID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public string SessionID { get; set; }
        public string IpAddress { get; set; }
        public string BrowserName { get; set; }
        public Nullable<int> LoginType { get; set; }
        public Nullable<System.DateTime> LogOutTime { get; set; }
        public Nullable<System.DateTime> LoginTime { get; set; }
        public bool IsLogin { get; set; }
        public string ApkDeviceName { get; set; }
        public string APKVersion { get; set; }
        public string Lattitude { get; set; }
        public string Longitude { get; set; }
    
        public virtual UserMaster UserMaster { get; set; }
    }
}
