//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccuIT.PersistenceLayer.Repository.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ECampaign
    {
        public int ECampaignID { get; set; }
        public string ECampaignName { get; set; }
        public string ECampaignSubject { get; set; }
        public string ECampaignLogoUrl { get; set; }
        public int TemplateID { get; set; }
        public string ECampaignContent { get; set; }
        public Nullable<int> Status { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public System.DateTime Created_Date { get; set; }
        public int Created_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public Nullable<int> Modified_By { get; set; }
        public Nullable<bool> Is_Deleted { get; set; }
        public Nullable<int> CategoryId { get; set; }
    }
}
