//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccuIT.PersistenceLayer.Repository.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginAttemptHistory
    {
        public long LoginAttemptID { get; set; }
        public Nullable<int> FailedAttempt { get; set; }
        public int UserID { get; set; }
        public Nullable<System.DateTime> LoginDate { get; set; }
        public Nullable<System.DateTime> LastLoginDate { get; set; }
        public string Lattitude { get; set; }
        public string Longitude { get; set; }
        public string IpAddress { get; set; }
        public string Browser { get; set; }
    
        public virtual UserMaster UserMaster { get; set; }
    }
}
