//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccuIT.PersistenceLayer.Repository.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModuleMaster
    {
        public ModuleMaster()
        {
            this.RoleModules = new HashSet<RoleModule>();
        }
    
        public int ModuleID { get; set; }
        public string Name { get; set; }
        public Nullable<int> ParentModuleID { get; set; }
        public Nullable<int> ModuleCode { get; set; }
        public bool IsMobile { get; set; }
        public int Sequence { get; set; }
        public int Status { get; set; }
        public bool IsSystemModule { get; set; }
        public string Icon { get; set; }
        public Nullable<bool> IsStoreWise { get; set; }
        public int ModuleType { get; set; }
        public string ModuleDescription { get; set; }
        public string PageURL { get; set; }
        public Nullable<bool> IsMandatory { get; set; }
        public bool IsDeleted { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual ICollection<RoleModule> RoleModules { get; set; }
    }
}
