//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccuIT.PersistenceLayer.Repository.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleMaster
    {
        public RoleMaster()
        {
            this.RoleModules = new HashSet<RoleModule>();
            this.UserRoles = new HashSet<UserRole>();
        }
    
        public int RoleID { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public Nullable<int> Type { get; set; }
        public int Status { get; set; }
        public bool IsAdmin { get; set; }
        public bool IsDeleted { get; set; }
        public string RoleDescription { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual ICollection<RoleModule> RoleModules { get; set; }
        public virtual ICollection<UserRole> UserRoles { get; set; }
    }
}
