//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccuIT.PersistenceLayer.Repository.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleModule
    {
        public RoleModule()
        {
            this.UserRoleModulePermissions = new HashSet<UserRoleModulePermission>();
        }
    
        public int RoleModuleID { get; set; }
        public int RoleID { get; set; }
        public int ModuleID { get; set; }
        public int Sequence { get; set; }
        public bool IsMandatory { get; set; }
        public bool IsDeleted { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual ModuleMaster ModuleMaster { get; set; }
        public virtual RoleMaster RoleMaster { get; set; }
        public virtual ICollection<UserRoleModulePermission> UserRoleModulePermissions { get; set; }
    }
}
