//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccuIT.PersistenceLayer.Repository.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemSetting
    {
        public int SettingID { get; set; }
        public int CompanyID { get; set; }
        public int LogoutTime { get; set; }
        public int LoginFailedAttempt { get; set; }
        public int MaxLeaveMarkDays { get; set; }
        public string WeeklyOffDays { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public long CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public int IdleSystemDay { get; set; }
    
        public virtual CompanyMaster CompanyMaster { get; set; }
    }
}
