//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccuIT.PersistenceLayer.Repository.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TemplateMaster
    {
        public TemplateMaster()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
            this.TemplateImages = new HashSet<TemplateImage>();
            this.TemplateMergeFields = new HashSet<TemplateMergeField>();
            this.TemplatePages = new HashSet<TemplatePage>();
            this.UserWeddingSubscriptions = new HashSet<UserWeddingSubscription>();
        }
    
        public int TemplateID { get; set; }
        public string TemplateName { get; set; }
        public int TemplateType { get; set; }
        public int TemplateStatus { get; set; }
        public string TemplateContent { get; set; }
        public string TemplateSubject { get; set; }
        public string TemplateTags { get; set; }
        public string TemplateUrl { get; set; }
        public string TemplateFolderPath { get; set; }
        public string ThumbnailImageUrl { get; set; }
        public string TagLine { get; set; }
        public Nullable<int> COST { get; set; }
        public string AuthorName { get; set; }
        public string AboutTemplate { get; set; }
        public string Features { get; set; }
        public bool IsDeleted { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBY { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> TemplateCode { get; set; }
    
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual ICollection<TemplateImage> TemplateImages { get; set; }
        public virtual ICollection<TemplateMergeField> TemplateMergeFields { get; set; }
        public virtual ICollection<TemplatePage> TemplatePages { get; set; }
        public virtual ICollection<UserWeddingSubscription> UserWeddingSubscriptions { get; set; }
    }
}
