//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccuIT.PersistenceLayer.Repository.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TemplateMergeField
    {
        public int PK_ID { get; set; }
        public string MERGEFIELD_NAME { get; set; }
        public string SRC_FIELD { get; set; }
        public string SRC_FIELD_VALUE { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> TemplateID { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> Sequence { get; set; }
        public Nullable<int> TemplateCode { get; set; }
    
        public virtual TemplateMaster TemplateMaster { get; set; }
    }
}
