//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccuIT.PersistenceLayer.Repository.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TemplatePage
    {
        public int PageID { get; set; }
        public string PageName { get; set; }
        public string Title { get; set; }
        public string PageContent { get; set; }
        public string PageUrl { get; set; }
        public string PageFolderPath { get; set; }
        public string ThumbnailImageUrl { get; set; }
        public int TemplateID { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual TemplateMaster TemplateMaster { get; set; }
    }
}
