//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccuIT.PersistenceLayer.Repository.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMaster
    {
        public UserMaster()
        {
            this.DailyLoginHistories = new HashSet<DailyLoginHistory>();
            this.LoginAttemptHistories = new HashSet<LoginAttemptHistory>();
            this.OrderMasters = new HashSet<OrderMaster>();
            this.UserDevices = new HashSet<UserDevice>();
            this.UserRoles = new HashSet<UserRole>();
            this.UserServiceAccesses = new HashSet<UserServiceAccess>();
            this.UserSystemSettings = new HashSet<UserSystemSetting>();
        }
    
        public int UserID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public bool isDeleted { get; set; }
        public string LoginName { get; set; }
        public string Password { get; set; }
        public string ImagePath { get; set; }
        public string EmpCode { get; set; }
        public string Email { get; set; }
        public Nullable<int> AccountStatus { get; set; }
        public bool isActive { get; set; }
        public Nullable<int> SeniorEmpID { get; set; }
        public Nullable<bool> IsEmployee { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string Phone { get; set; }
        public string Mobile { get; set; }
        public int CompanyId { get; set; }
    
        public virtual CompanyMaster CompanyMaster { get; set; }
        public virtual ICollection<DailyLoginHistory> DailyLoginHistories { get; set; }
        public virtual ICollection<LoginAttemptHistory> LoginAttemptHistories { get; set; }
        public virtual ICollection<OrderMaster> OrderMasters { get; set; }
        public virtual ICollection<UserDevice> UserDevices { get; set; }
        public virtual ICollection<UserRole> UserRoles { get; set; }
        public virtual ICollection<UserServiceAccess> UserServiceAccesses { get; set; }
        public virtual ICollection<UserSystemSetting> UserSystemSettings { get; set; }
    }
}
