//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccuIT.PersistenceLayer.Repository.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRoleModulePermission
    {
        public long UserRolePermissionID { get; set; }
        public Nullable<int> RoleModuleID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> ModuleID { get; set; }
        public int PermissionID { get; set; }
        public string PermissionValue { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual RoleModule RoleModule { get; set; }
    }
}
