//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccuIT.PersistenceLayer.Repository.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserWeddingSubscription
    {
        public int UserWeddingSubscrptionID { get; set; }
        public int UserId { get; set; }
        public int TemplateID { get; set; }
        public Nullable<int> InvoiceNo { get; set; }
        public Nullable<int> WeddingID { get; set; }
        public int SubscriptionType { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string ReasonOfUpdate { get; set; }
        public int SubscriptionStatus { get; set; }
    
        public virtual OrderMaster OrderMaster { get; set; }
        public virtual SubscriptionMaster SubscriptionMaster { get; set; }
        public virtual TemplateMaster TemplateMaster { get; set; }
        public virtual Wedding Wedding { get; set; }
    }
}
