//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccuIT.PersistenceLayer.Repository.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venue
    {
        public int VenueID { get; set; }
        public string Name { get; set; }
        public string VenueImageUrl { get; set; }
        public string VenueBannerImageUrl { get; set; }
        public string VenueWebsite { get; set; }
        public string OwnerName { get; set; }
        public string VenuePhone { get; set; }
        public string VenueMobile { get; set; }
        public Nullable<int> WeddingEventID { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsActive { get; set; }
        public string googleMapUrl { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual WeddingEvent WeddingEvent { get; set; }
    }
}
