//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccuIT.PersistenceLayer.Repository.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwGetUserWeddingTemplate
    {
        public int UserID { get; set; }
        public Nullable<int> AccountStatus { get; set; }
        public int OrderID { get; set; }
        public Nullable<int> WeddingID { get; set; }
        public int TemplateID { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<int> UserWeddingSubscrptionID { get; set; }
        public decimal Amount { get; set; }
        public string OrderStatus { get; set; }
        public Nullable<int> PaymentMode { get; set; }
        public Nullable<int> Discount { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> SubscriptionType { get; set; }
        public Nullable<int> SubscriptionStatus { get; set; }
        public string TemplateName { get; set; }
        public string TemplateFolderPath { get; set; }
        public string ThumbnailImageUrl { get; set; }
        public Nullable<System.DateTime> WeddingDate { get; set; }
        public string Title { get; set; }
        public string BackgroundImage { get; set; }
    }
}
