//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccuIT.PersistenceLayer.Repository.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwGetUserRoleModule
    {
        public int ModuleID { get; set; }
        public string Name { get; set; }
        public Nullable<int> ParentModuleID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> MaxModifiedDate { get; set; }
        public Nullable<bool> IsMandatory { get; set; }
        public Nullable<int> ModuleCode { get; set; }
        public string Icon { get; set; }
        public Nullable<bool> IsStoreWise { get; set; }
        public int Sequence { get; set; }
        public string PageURL { get; set; }
        public int ModuleType { get; set; }
        public bool IsMobile { get; set; }
        public bool IsDeleted { get; set; }
    }
}
