USE DreamWedds



CREATE TABLE [dbo].[UserMaster]				    ( [UserID] [INT] NOT NULL IDENTITY(1,1) PRIMARY KEY, [FirstName] [VARCHAR](40)   NOT NULL  , [LastName] [VARCHAR](50) NOT  NULL , [isDeleted] [BIT] NOT NULL , [LoginName] [VARCHAR](150)   NULL , [Password] [VARCHAR](30)   NULL , [Salary] [DECIMAL](10,2) NULL , [JoiningDate] [DATE] NULL , [ImagePath] [VARCHAR](750)   NULL , [UserCode] [VARCHAR](20)   NULL , [Email] [VARCHAR](250)   NULL , [Phone] [VARCHAR](20)   NULL , [Mobile] [VARCHAR](20)   NULL , [AccountStatus] [INT] NULL , [isActive] [BIT] NULL , [SeniorEmpID] [INT] NULL , [IsEmployee] [BIT] NULL  , [CreatedDate] [DATETIME] NULL , [CreatedBy] [INT] NOT NULL , [ModifiedDate] [DATETIME] NULL , [ModifiedBy] [INT] NULL );
CREATE TABLE [dbo].[RoleMaster]				    ( [RoleID] [INT] NOT NULL IDENTITY(1,1)  PRIMARY KEY, [Name] [VARCHAR](50)   NOT NULL , [Code] [VARCHAR](50)   NOT NULL , [Type] [INT] NULL , [Status] [INT] NOT NULL , [IsAdmin] [BIT] NOT NULL , [IsDeleted] [BIT] NOT NULL , [RoleDescription] [VARCHAR](250)   NULL , [CreatedBy] [INT] NOT NULL , [ModifiedBy] [INT] NULL , [CreatedDate] [DATETIME] NULL , [ModifiedDate] [DATETIME] NULL  );
CREATE TABLE [dbo].[CommonSetup]				( [CommonSetupID] [INT] NOT NULL IDENTITY(1,1) PRIMARY KEY , [MainType] [VARCHAR](50)   NOT NULL , [SubType] [VARCHAR](50)   NOT NULL , [DisplayText] [VARCHAR](150)   NOT NULL , [DisplayValue] [INT] NOT NULL , [ParentID] [INT] NOT NULL , [CreatedDate] [DATETIME] NOT NULL , [ModifiedDate] [DATETIME] NULL , [isDeleted] [BIT] NULL );
CREATE TABLE [dbo].[UserRoles]				    ( [UserRoleID] [INT] NOT NULL IDENTITY(1,1)  PRIMARY KEY, [RoleID] [INT] NOT NULL FOREIGN KEY REFERENCES RoleMaster(RoleID) , [UserID] [INT] NULL FOREIGN KEY REFERENCES UserMaster(UserID), [IsActive] [BIT] NOT NULL , [isDeleted] [BIT] NOT NULL  , [CreatedBy] [INT] NOT NULL , [ModifiedBy] [INT] NULL , [CreatedDate] [DATETIME] NOT NULL , [ModifiedDate] [DATETIME] NULL );

CREATE TABLE [dbo].[ModuleMaster]				( [ModuleID] [INT] NOT NULL IDENTITY(1,1)  PRIMARY KEY, [Name] [VARCHAR](150)   NOT NULL , [ParentModuleID] [INT] NULL , [ModuleCode] [INT] NULL , [IsMobile] [BIT] NOT NULL , [Sequence] [INT] NOT NULL , [Status] [INT] NOT NULL , [IsSystemModule] [BIT] NOT NULL , [Icon] [VARCHAR](200)   NULL , [IsStoreWise] [BIT] NULL , [ModuleType] [INT] NOT NULL , [ModuleDescription] [VARCHAR](250)   NOT NULL , [PageURL] [VARCHAR](350)   NOT NULL , [IsMandatory] [BIT] NULL , [IsDeleted] [BIT] NOT NULL, [CreatedBy] [INT] NOT NULL , [ModifiedBy] [INT] NULL , [CreatedDate] [DATETIME] NOT NULL , [ModifiedDate] [DATETIME] NULL  );
CREATE TABLE [dbo].[RoleModule]					( [RoleModuleID] [INT] NOT NULL IDENTITY(1,1)  PRIMARY KEY , [RoleID] [INT] NOT NULL , [ModuleID] [INT] NOT NULL , [Sequence] [INT] NOT NULL , [IsMandatory] [BIT] NOT NULL , [IsDeleted] [BIT] NOT NULL , [CreatedBy] [INT] NOT NULL , [ModifiedBy] [INT] NULL , [CreatedDate] [DATETIME] NOT NULL , [ModifiedDate] [DATETIME] NULL );
CREATE TABLE [dbo].[Permissions]				( [PermissionID] [INT] NOT NULL IDENTITY(1,1) PRIMARY KEY , [PermissionValue] [VARCHAR](150)   NOT NULL );
CREATE TABLE [dbo].[UserRoleModulePermission]   ( [UserRolePermissionID] [BIGINT] NOT NULL IDENTITY(1,1) PRIMARY KEY , [RoleModuleID] [INT] NULL , [UserID] [INT] NULL , [ModuleID] [INT] NULL , [PermissionID] [INT] NOT NULL , [PermissionValue] [VARCHAR](150)   NOT NULL , [CreatedBy] [INT] NOT NULL , [ModifiedBy] [INT] NULL , [CreatedDate] [DATETIME] NOT NULL , [ModifiedDate] [DATETIME] NULL  );
CREATE TABLE [dbo].[ErrorLog]					( [LogID] [INT] NOT NULL IDENTITY(1,1) PRIMARY KEY , [EventID] [INT] NULL , [Priority] [INT] NOT NULL , [Severity] [INT] NOT NULL , [Title] [VARCHAR](150)   NULL , [MachineName] [VARCHAR](150)   NULL , [AppDomainName] [VARCHAR](150)   NULL , [ProcessID] [VARCHAR](150)   NULL , [ProcessName] [VARCHAR](150)   NULL , [ThreadName] [VARCHAR](150)   NULL , [Win32ThreadId] [VARCHAR](150)   NULL , [Message] [VARCHAR](MAX)   NULL , [Timestamp] [DATETIME] NOT NULL , [FormattedMessage] [VARCHAR](1000)   NULL  );
CREATE TABLE [dbo].[LoginAttemptHistory]	    ( [LoginAttemptID] [BIGINT] NOT NULL IDENTITY(1,1) PRIMARY KEY , [FailedAttempt] [INT] NULL , [UserID] [INT] NOT NULL ,  [LoginDate] [DATETIME] NULL , [LastLoginDate] [DATETIME] NULL , [Lattitude] [VARCHAR](30)   NULL , [Longitude] [VARCHAR](30)   NULL , [IpAddress] [VARCHAR](30)   NULL , [Browser] [VARCHAR](30)   NULL );
CREATE TABLE [dbo].[OTPMaster]					( [OTPMasterID] [BIGINT] NOT NULL IDENTITY(1,1) PRIMARY KEY , [UserID] [INT] NOT NULL , [OTP] [VARCHAR](10)   NOT NULL , [GUID] [VARCHAR](150)   NULL , [CreatedDate] [DATETIME] NOT NULL , [Attempts] [INT] NULL );

CREATE TABLE [dbo].[TemplateMaster]				( [TemplateID] [INT] NOT NULL IDENTITY(1,1) PRIMARY KEY , [TemplateName] [NVARCHAR](150)  NOT NULL , [TemplateType] [INT] NOT NULL , [TemplateStatus] [INT] NOT NULL , [TemplateContent] [VARCHAR](MAX)  NOT NULL , [TemplateSubject] [VARCHAR](250) NULL , [TemplateTags] [VARCHAR](15)  NULL , [TemplateUrl] [VARCHAR](1000)  NULL , [TemplateFolderPath] [VARCHAR](500)  NULL , [ThumbnailImageUrl] [VARCHAR](1000) NULL , [TagLine] [VARCHAR](500)  NULL , [COST] [INT] NULL , [AuthorName] [VARCHAR](100) NULL , [AboutTemplate] [VARCHAR](1000)  NULL , [Features] [VARCHAR](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL , [IsDeleted] [BIT] NULL, [CREATED_BY] [INT] NOT NULL , [Created_Date] [DATETIME] NOT NULL  , [ModifiedBY] [INT] NULL , [ModifiedDate] [DATETIME] NULL  );
CREATE TABLE [dbo].[TemplateImages]				( [ImageID] [INT] NOT NULL IDENTITY(1,1) PRIMARY KEY , [ImageName] [VARCHAR](150)   NOT NULL , [ImageTitle] [VARCHAR](250)   NULL , [ImageTagLine] [VARCHAR](MAX)   NULL , [ImageUrl] [VARCHAR](1000)   NULL , [ImageFolderPath] [VARCHAR](1000)   NOT NULL , [IsBannerImage] [BIT] NOT NULL , [TemplateID] [INT] NOT NULL   FOREIGN KEY REFERENCES TemplateMaster(TemplateID), [CreatedBy] [INT] NOT NULL , [ModifiedBy] [INT] NULL , [CreatedDate] [DATETIME] NOT NULL , [ModifiedDate] [DATETIME] NULL , [ImageType] [INT] NULL  );
CREATE TABLE [dbo].[TemplatePages]				( [PageID] [INT] NOT NULL IDENTITY(1,1) PRIMARY KEY , [PageName] [VARCHAR](150)   NOT NULL , [Title] [VARCHAR](250)   NOT NULL , [PageContent] [VARCHAR](MAX)   NOT NULL , [PageUrl] [VARCHAR](500)   NULL , [PageFolderPath] [VARCHAR](500)   NOT NULL , [ThumbnailImageUrl] [VARCHAR](500)   NULL , [TemplateID] [INT] NOT NULL   FOREIGN KEY REFERENCES TemplateMaster(TemplateID), [CreatedBy] [INT] NOT NULL , [ModifiedBy] [INT] NULL , [CreatedDate] [DATETIME] NOT NULL , [ModifiedDate] [DATETIME] NULL  );

CREATE TABLE [dbo].[FAQ]						( [FAQID] [INT] NOT NULL IDENTITY(1,1) PRIMARY KEY , [Question] [VARCHAR](500)   NOT NULL , [Answer] [VARCHAR](1500)   NOT NULL , [Website] [VARCHAR](250)   NOT NULL , [IsMainQue] [BIT] NOT NULL , [sequence] [INT] NULL  );
CREATE TABLE [dbo].[OrderMaster]				( [OrderID] [INT] NOT NULL , [CustomerID] [INT] NULL , [OrderDate] [DATETIME] NULL , [RequiredDate] [DATETIME] NULL  , [OrderStatus] [VARCHAR](40)   NULL , [AddressID] [VARCHAR](60)   NULL , [CGST] [INT] NULL , [SGST] [INT] NULL ,  [Discount] [INT] NULL, [Amount] [MONEY] NOT NULL, [ReceivedAmount] [MONEY] NULL , [PaymentMode] [INT] NULL , [PaymentTerms] [VARCHAR](50)   NULL , [OderNote] [VARCHAR](250)   NULL , [CreatedDate] [DATETIME] NOT NULL , [CreatedBy] [INT] NOT NULL , [ModifiedDate] [DATETIME] NULL , [ModifiedBy] [INT] NULL , [Is_Deleted] [BIT] NULL);
CREATE TABLE [dbo].[Weddings]					( [WeddingID] [INT] NOT NULL IDENTITY(1,1) PRIMARY KEY , [WeddingDate] [DATETIME] NOT NULL , [Title] [VARCHAR](150)   NOT NULL , [WeddingStyle] [INT] NOT NULL , [IconUrl] [VARCHAR](500)   NULL , [TemplateID] [INT] NULL , [IsLoveMarriage] [BIT] NOT NULL CONSTRAINT [DF__Weddings__IsLove__4924D839] DEFAULT ((0)) , [UserID] [INT] NULL , [IsDeleted] [BIT] NULL , [IsActive] [BIT] NULL , [BackgroundImage] [VARCHAR](1000)   NULL , [Quote] [VARCHAR](500)   NULL , [fbPageUrl] [VARCHAR](1500)   NULL , [videoUrl] [VARCHAR](1500)   NULL  , [CreatedBy] [INT] NOT NULL , [ModifiedBy] [INT] NULL , [CreatedDate] [DATETIME] NOT NULL , [ModifiedDate] [DATETIME] NULL);

CREATE TABLE [dbo].[BrideAndMaid]				( [BrideAndMaidID] [INT] NOT NULL IDENTITY(1,1) PRIMARY KEY , [FirstName] [VARCHAR](150)  NOT NULL , [LastName] [VARCHAR](150)  NOT NULL , [DateofBirth] [DATETIME] NULL , [WeddingID] [INT] NOT NULL FOREIGN KEY REFERENCES Weddings(WeddingID), [IsBride] [BIT] NOT NULL , [RelationWithBride] [INT] NULL , [Imageurl] [VARCHAR](500)   NULL , [CreatedBy] [INT] NOT NULL , [ModifiedBy] [INT] NULL ,  [AboutBrideMaid] [VARCHAR](500)  NULL , [IsDeleted] [BIT] NULL , [fbUrl] [VARCHAR](1500)   NULL , [googleUrl] [VARCHAR](1500)   NULL , [instagramUrl] [VARCHAR](1500)   NULL , [lnkedinUrl] [VARCHAR](1500)   NULL ,[CreatedDate] [DATETIME] NOT NULL , [ModifiedDate] [DATETIME] NULL );
CREATE TABLE [dbo].[GroomAndMen]				( [GroomAndMenID] [INT] NOT NULL IDENTITY(1,1) PRIMARY KEY , [FirstName] [VARCHAR](150)   NOT NULL , [LastName] [VARCHAR](150)   NOT NULL , [DateofBirth] [DATETIME] NULL , [WeddingID] [INT] NOT NULL FOREIGN KEY REFERENCES Weddings(WeddingID), [IsGroom] [BIT] NOT NULL , [RelationWithGroom] [INT] NULL , [Imageurl] [VARCHAR](500)   NULL , [CreatedBy] [INT] NOT NULL , [ModifiedBy] [INT] NULL , [CreatedDate] [DATETIME] NOT NULL , [ModifiedDate] [DATETIME] NULL , [AboutMen] [VARCHAR](500)   NULL , [IsDeleted] [BIT] NULL , [fbUrl] [VARCHAR](1500)   NULL , [googleUrl] [VARCHAR](1500)   NULL , [instagramUrl] [VARCHAR](1500)   NULL , [lnkedinUrl] [VARCHAR](1500)   NULL );
CREATE TABLE [dbo].[Venue]						( [VenueID] [INT] NOT NULL IDENTITY(1,1) PRIMARY KEY , [Name] [VARCHAR](150)   NOT NULL, [VenueImageUrl] [VARCHAR](350)   NULL , [VenueBannerImageUrl] [VARCHAR](1000)   NULL , [VenueWebsite] [VARCHAR](500)   NULL , [OwnerName] [VARCHAR](50)   NULL , [VenuePhone] [VARCHAR](15)   NULL , [VenueMobile] [VARCHAR](15)   NULL , [WeddingEventID] [INT] NULL , [IsDeleted] [BIT] NULL , [IsActive] [BIT] NULL , [AddressID] [INT] NULL , [googleMapUrl] [VARCHAR](1500)   NULL  , [CreatedBy] [INT] NOT NULL , [ModifiedBy] [INT] NULL , [CreatedDate] [DATETIME] NOT NULL , [ModifiedDate] [DATETIME] NULL  );
CREATE TABLE [dbo].[WeddingEvents]				( [WeddingEventID] [INT] NOT NULL IDENTITY(1,1) PRIMARY KEY , [EventDate] [DATETIME] NOT NULL , [Title] [VARCHAR](250)   NOT NULL , [WeddingID] [INT] NOT NULL  FOREIGN KEY REFERENCES Weddings(WeddingID), [ImageUrl] [VARCHAR](500)   NULL , [CreatedBy] [INT] NOT NULL , [ModifiedBy] [INT] NULL , [IsActive] [BIT] NOT NULL , [IsDeleted] [BIT] NOT NULL, [StartTime] [DATETIME] NOT NULL , [EndTime] [DATETIME] NOT NULL , [Aboutevent] [VARCHAR](1000)   NULL , [BackGroundImage] [VARCHAR](1000)   NULL  , [CreatedDate] [DATETIME] NOT NULL , [ModifiedDate] [DATETIME] NULL );
CREATE TABLE [dbo].[WeddingGallery]				( [WeddingGalleryID] [INT] NOT NULL IDENTITY(1,1) PRIMARY KEY , [Title] [VARCHAR](250)   NULL , [WeddingID] [INT] NOT NULL  FOREIGN KEY REFERENCES Weddings(WeddingID), [ImageUrl] [VARCHAR](MAX)   NULL , [CreatedBy] [INT] NOT NULL , [CreatedDate] [DATETIME] NOT NULL );
CREATE TABLE [dbo].[UserTemplates]				( [UserTemplateID] [INT] NOT NULL IDENTITY(1,1) PRIMARY KEY , [UserId] [INT] NOT NULL , [TemplateID] [INT] NOT NULL , [PurchaseDate] [DATETIME] NOT NULL , [InvoiceNo] [INT] NULL , [WeddingID] [INT] NULL FOREIGN KEY REFERENCES Weddings(WeddingID) );
CREATE TABLE [dbo].[RSVPDetails]				( [RSVPID] [INT] NOT NULL IDENTITY(1,1) PRIMARY KEY , [FirstName] [VARCHAR](50)   NOT NULL , [MiddleName] [VARCHAR](50)   NULL , [LastName] [VARCHAR](50)   NOT NULL , [IsComing] [BIT] NOT NULL , [FromDate] [DATETIME] NULL , [ToDate] [DATETIME] NULL , [GuestCount] [INT] NULL , [PreferredFood] [TINYINT] NOT NULL , [Email] [VARCHAR](150)   NULL , [Phone] [VARCHAR](15)   NULL , [Mobile] [VARCHAR](15)   NULL , [SpecialNote] [VARCHAR](500)   NULL , [ImageUrl] [VARCHAR](500)   NOT NULL , [IsDeleted] [BIT] NOT NULL , [WeddingID] [INT] NOT NULL , [ParticipatingInEvents] [VARCHAR](20)   NULL , [ComingFromCity] [VARCHAR](150)   NULL , [PreferredStayIn] [INT] NULL , [CreatedDate] [DATETIME] NOT NULL , [ModifiedDate] [DATETIME] NULL , [ModifiedBy] [INT] NULL , [CreatedBy] [INT] NULL );
CREATE TABLE [dbo].[TimeLine]					( [TimeLineID] [INT] NOT NULL IDENTITY(1,1) PRIMARY KEY , [StoryDate] [DATETIME] NOT NULL , [Title] [VARCHAR](150)   NOT NULL , [Story] [VARCHAR](2000)   NULL , [ImageUrl] [VARCHAR](1000)   NULL , [WeddingID] [INT] NOT NULL  FOREIGN KEY REFERENCES Weddings(WeddingID), [CreatedBy] [INT] NOT NULL , [ModifiedBy] [INT] NULL , [CreatedDate] [DATETIME] NOT NULL , [ModifiedDate] [DATETIME] NULL , [Location] [VARCHAR](500)   NULL);

CREATE TABLE [dbo].[ECampaign]					( [ECampaignID] [INT] NOT NULL IDENTITY(1,1) PRIMARY KEY , [ECampaignName] [VARCHAR](100)   NULL , [ECampaignSubject] [VARCHAR](250)   NULL , [ECampaignLogoUrl] [VARCHAR](550)   NULL , [TemplateID] [INT] NOT NULL , [ECampaignContent] [VARCHAR](MAX)   NULL , [Status] [INT] NULL , [StartDate] [DATETIME] NOT NULL , [EndDate] [DATETIME] NULL , [Created_Date] [DATETIME] NOT NULL , [Created_By] [INT] NOT NULL , [Modified_Date] [DATETIME] NULL , [Modified_By] [INT] NULL , [Is_Deleted] [BIT] NULL , [CategoryId] [INT] NULL );
CREATE TABLE [dbo].[AddressMaster]				( [AddressID] [INT] NOT NULL IDENTITY(1,1) PRIMARY KEY , [Address1] [VARCHAR](150)   NULL , [Address2] [VARCHAR](150)   NULL , [City] [NVARCHAR](50)   NULL , [State] [NVARCHAR](50)   NOT NULL , [Country] [INT] NOT NULL , [PinCode] [INT] NOT NULL , [AddressType] [INT] NULL , [AddressStatus] [INT] NULL , [Created_Date] [DATETIME] NOT NULL , [Created_By] [INT] NOT NULL , [Modified_Date] [DATETIME] NULL , [Modified_By] [INT] NULL , [Is_Deleted] [BIT] NULL , [CustomerID] [INT] NULL , [AddressOwnerType] [INT] NULL , [AddressOwnerTypePKID] [INT] NULL , [VenueID] [INT] NULL);
CREATE TABLE [dbo].[DailyLoginHistory]			( [DailyLoginID] [BIGINT] NOT NULL IDENTITY(1,1) PRIMARY KEY , [UserID] [INT] NULL , [CustomerID] [INT] NULL , [SessionID] [VARCHAR](200)   NULL , [IpAddress] [VARCHAR](50)   NULL , [BrowserName] [VARCHAR](30)   NULL , [LoginType] [INT] NULL , [LogOutTime] [DATETIME] NULL , [LoginTime] [DATETIME] NULL , [IsLogin] [BIT] NOT NULL);
CREATE TABLE [dbo].[EmailService]				( [EmailServiceID] [BIGINT] NOT NULL IDENTITY(1,1) PRIMARY KEY , [TemplateID] [INT] NOT NULL , [FromEmail] [VARCHAR](150)   NOT NULL , [FromName] [VARCHAR](150)   NOT NULL , [ToName] [VARCHAR](150)   NOT NULL , [ToEmail] [VARCHAR](150)   NOT NULL , [CcEmail] [VARCHAR](150)   NULL , [BccEmail] [VARCHAR](150)  NULL , [Subject] [VARCHAR](250)   NOT NULL , [Body] [VARCHAR](MAX)   NOT NULL , [IsHtml] [BIT] NOT NULL , [Priority] [INT] NOT NULL , [Status] [INT] NOT NULL , [IsAttachment] [BIT] NOT NULL , [CreatedDate] [DATETIME] NOT NULL , [AttachmentFileName] [VARCHAR](50)   NULL , [Remarks] [VARCHAR](250)   NULL , [Mobile] [VARCHAR](15)   NULL , [Phone] [VARCHAR](15)   NULL , [MEssage] [VARCHAR](500)  NULL , [Location] [VARCHAR](50) NULL );

CREATE VIEW dbo.vwGetUserRoleModule
AS SELECT m.ModuleID, m.Name, m.ParentModuleID, er.UserID, Max(m.ModifiedDate) As MaxModifiedDate, m.IsMandatory, m.ModuleCode, m.Icon, m.IsStoreWise, m.Sequence, m.PageURL, m.ModuleType, m.IsMobile, rm.IsDeleted
FROM ModuleMaster m 
INNER JOIN RoleModule rm ON (m.ModuleID = rm.ModuleID)
INNER JOIN UserRoles (NOLOCK) er ON (er.RoleID = rm.RoleID)
GROUP BY m.ModuleID, m.Name, m.ParentModuleID, er.UserID, m.IsMandatory, m.ModuleCode, m.Icon, m.IsStoreWise, m.Sequence, m.PageURL, m.ModuleType, m.IsMobile, rm.IsDeleted
 


CREATE VIEW dbo.vwGetUserWeddingTemplates
AS SELECT ut.usertemplateID, ut.userID, ut.templateID, ut.purchasedate, ut.invoiceno, tm.templatename, tm.templatefolderpath, 
tm.ThumbnailImageUrl, tm.TagLine, tm.IsDeleted IsDeletedTemplate,  w.weddingId, w.WeddingDate, w.title, w.weddingstyle, w.iconurl, w.isLoveMarriage, w.modifiedDate , w.IsDeleted IsDeletedWedding, w.IsActive 
from  UserTemplates ut
INNER JOIN  TemplateMaster tm ON tm.TemplateID = ut.TemplateID
LEFT JOIN Weddings w ON w.templateid = tm.templateid AND w.isdeleted = 0



ALTER TABLE UserRoles ADD CONSTRAINT FK_UserRoles_UserID FOREIGN KEY (UserID) REFERENCES UserMaster(UserID);







